### ISSUE TITLE
 commit looked like it worked but then isn't showing up in github

### ISSUE THREAD

**Issue by vhodes** [vhodes/cseuli#1]
![git_com_cseuli](https://user-images.githubusercontent.com/50457206/58213943-d2882b00-7ca8-11e9-9c78-22d2fd55d3fc.PNG)

**Comment by cgrandin** [comment]
When you see the green arrow up it means you need to do
```
git push
```

**Comment by cgrandin** [comment]
Also when you write a commit message you need quotes around it. I’m not sure what will happen when you push that

**Comment by vhodes** [comment]
Thanks Chris!  I knew I had just missed a step.  Looks like it worked.
