### ISSUE TITLE
there is no package called gfdata. when trying to knit

### ISSUE THREAD

**Issue by vhodes** [vhodes/cseuli#2]
Everyday a new issue...Today my knit function isn't working.  It was fine for a while then all of a sudden it couldn't detect GFData.  Could this have something to do with code I pasted in from another project?

![image](https://user-images.githubusercontent.com/50457206/58282883-d45ef680-7d5b-11e9-9837-a6d23f856038.png)

**Comment by cgrandin** [comment]
You need to clone gfdata - just like the other packages. make sure you're in C:\github and do this:
```
git clone https://github.com/pbs-assess/gfdata
```
Then open the gfdata.Rproj in Rstudio and Build->Install and Restart (or Ctrl-shift-B).
It should work after that

**Comment by vhodes** [comment]
I was thinking of trying that then I chickened out thinking it might break something else!  Thanks!
